<?php

namespace Database\Seeders;

use App\Models\Drink;
use Illuminate\Database\Seeder;

class DrinkSeeder extends Seeder
{
    public function run(): void
    {
        $drinks = [
            [
                'name' => 'Эспрессо',
                'slug' => 'espresso',
                'catalog' => 'menu',
                'category_key' => 'classic',
                'category_name' => 'Классика',
                'description' => 'Крепкий и насыщенный шот для бодрого старта без лишнего.',
                'ingredients' => '100% арабика, вода.',
                'volume' => '30 мл',
                'price' => 130,
                'size_options' => [
                    ['label' => '30 мл', 'price' => 130],
                ],
                'image_path' => 'media/images/эспрессо.jpg',
                'sort_order' => 10,
            ],
            [
                'name' => 'Американо',
                'slug' => 'americano',
                'catalog' => 'menu',
                'category_key' => 'classic',
                'category_name' => 'Классика',
                'description' => 'Чистый вкус кофе, мягче по плотности и отлично на каждый день.',
                'ingredients' => 'Эспрессо, вода.',
                'volume' => 'S / M / L',
                'price' => 170,
                'size_options' => [
                    ['label' => 'S', 'price' => 170],
                    ['label' => 'M', 'price' => 190],
                    ['label' => 'L', 'price' => 210],
                ],
                'image_path' => 'media/images/американо.jpg',
                'sort_order' => 20,
            ],
            [
                'name' => 'Капучино',
                'slug' => 'cappuccino',
                'catalog' => 'menu',
                'category_key' => 'milk',
                'category_name' => 'На молоке',
                'description' => 'Воздушная молочная текстура и сбалансированный кофейный вкус.',
                'ingredients' => 'Эспрессо, молоко.',
                'volume' => 'S / M / L',
                'price' => 220,
                'size_options' => [
                    ['label' => 'S', 'price' => 220],
                    ['label' => 'M', 'price' => 240],
                    ['label' => 'L', 'price' => 260],
                ],
                'image_path' => 'media/images/капучино.jpg',
                'sort_order' => 30,
            ],
            [
                'name' => 'Латте',
                'slug' => 'latte',
                'catalog' => 'menu',
                'category_key' => 'milk',
                'category_name' => 'На молоке',
                'description' => 'Мягкий и сливочный напиток для долгого медленного глотка.',
                'ingredients' => 'Эспрессо, молоко.',
                'volume' => 'M / L / XL',
                'price' => 250,
                'size_options' => [
                    ['label' => 'M', 'price' => 250],
                    ['label' => 'L', 'price' => 280],
                    ['label' => 'XL', 'price' => 310],
                ],
                'image_path' => 'media/images/латте.jpg',
                'sort_order' => 40,
            ],
            [
                'name' => 'Флэт уайт',
                'slug' => 'flat-white',
                'catalog' => 'menu',
                'category_key' => 'milk',
                'category_name' => 'На молоке',
                'description' => 'Плотный кофейный вкус и тонкая молочная текстура для тех, кто любит ярче.',
                'ingredients' => 'Двойной эспрессо, молоко.',
                'volume' => 'S / M',
                'price' => 230,
                'size_options' => [
                    ['label' => 'S', 'price' => 230],
                    ['label' => 'M', 'price' => 260],
                ],
                'image_path' => 'media/images/флэт-вайт.jpg',
                'sort_order' => 50,
            ],
            [
                'name' => 'Раф классический',
                'slug' => 'raf-classic',
                'catalog' => 'menu',
                'category_key' => 'signature',
                'category_name' => 'Авторские',
                'description' => 'Кремовый раф с мягким сливочным вкусом и уютной подачей.',
                'ingredients' => 'Эспрессо, сливки, молоко, ванильный сахар.',
                'volume' => 'M / L',
                'price' => 290,
                'size_options' => [
                    ['label' => 'M', 'price' => 290],
                    ['label' => 'L', 'price' => 320],
                ],
                'image_path' => 'media/images/раф.jpg',
                'sort_order' => 60,
            ],
            [
                'name' => 'Раф малина-кокос',
                'slug' => 'raf-raspberry-coconut',
                'catalog' => 'menu',
                'category_key' => 'signature',
                'category_name' => 'Авторские',
                'description' => 'Ягодный раф с нежной кокосовой нотой и мягким десертным вкусом.',
                'ingredients' => 'Эспрессо, сливки, молоко, сироп малина, кокосовый сироп.',
                'volume' => 'M / L',
                'price' => 320,
                'size_options' => [
                    ['label' => 'M', 'price' => 320],
                    ['label' => 'L', 'price' => 350],
                ],
                'image_path' => 'media/images/раф-малина-кокос.jpg',
                'sort_order' => 70,
            ],
            [
                'name' => 'Раф Птичье молоко',
                'slug' => 'raf-birds-milk',
                'catalog' => 'menu',
                'category_key' => 'signature',
                'category_name' => 'Авторские',
                'description' => 'Нежный сладкий раф с вкусом знакомого десерта и бархатной текстурой.',
                'ingredients' => 'Эспрессо, сливки, молоко, сироп птичье молоко.',
                'volume' => 'M / L',
                'price' => 330,
                'size_options' => [
                    ['label' => 'M', 'price' => 330],
                    ['label' => 'L', 'price' => 360],
                ],
                'image_path' => 'media/images/раф-птичье-молоко.jpg',
                'sort_order' => 80,
            ],
            [
                'name' => 'Раф фисташковый тарт',
                'slug' => 'raf-pistachio-tart',
                'catalog' => 'menu',
                'category_key' => 'signature',
                'category_name' => 'Авторские',
                'description' => 'Яркий десертный раф с фисташковой нотой, рикоттой и клюквенным акцентом.',
                'ingredients' => 'Эспрессо, сливки, молоко, фисташковый сироп, сироп рикотта, клюквенный топпинг.',
                'volume' => 'M / L',
                'price' => 340,
                'size_options' => [
                    ['label' => 'M', 'price' => 340],
                    ['label' => 'L', 'price' => 370],
                ],
                'image_path' => 'media/images/Раф-Фисташковый-тарт-с-рикоттой-и-клюквой.jpg',
                'sort_order' => 90,
            ],
            [
                'name' => 'Айс латте',
                'slug' => 'iced-latte',
                'catalog' => 'menu',
                'category_key' => 'cold-coffee',
                'category_name' => 'Холодный кофе',
                'description' => 'Освежающий кофе со льдом для теплого дня и быстрого темпа.',
                'ingredients' => 'Эспрессо, молоко, лед.',
                'volume' => 'M / L / XL',
                'price' => 260,
                'size_options' => [
                    ['label' => 'M', 'price' => 260],
                    ['label' => 'L', 'price' => 290],
                    ['label' => 'XL', 'price' => 320],
                ],
                'image_path' => 'media/images/айс-латте.jpg',
                'sort_order' => 100,
            ],
            [
                'name' => 'Айс капучино',
                'slug' => 'iced-cappuccino',
                'catalog' => 'menu',
                'category_key' => 'cold-coffee',
                'category_name' => 'Холодный кофе',
                'description' => 'Освежающая молочная кофейная классика со льдом и мягкой пеной.',
                'ingredients' => 'Эспрессо, молоко, лед.',
                'volume' => 'M / L',
                'price' => 250,
                'size_options' => [
                    ['label' => 'M', 'price' => 250],
                    ['label' => 'L', 'price' => 280],
                ],
                'image_path' => 'media/images/айс-капучно.jpg',
                'sort_order' => 110,
            ],
            [
                'name' => 'Айс раф',
                'slug' => 'iced-raf',
                'catalog' => 'menu',
                'category_key' => 'cold-coffee',
                'category_name' => 'Холодный кофе',
                'description' => 'Холодный кремовый раф для тех, кто любит мягкий вкус даже летом.',
                'ingredients' => 'Эспрессо, сливки, молоко, лед.',
                'volume' => 'M / L',
                'price' => 300,
                'size_options' => [
                    ['label' => 'M', 'price' => 300],
                    ['label' => 'L', 'price' => 330],
                ],
                'image_path' => 'media/images/айс-раф.jpg',
                'sort_order' => 120,
            ],
            [
                'name' => 'Какао',
                'slug' => 'cocoa',
                'catalog' => 'menu',
                'category_key' => 'non-coffee',
                'category_name' => 'Без кофе',
                'description' => 'Насыщенный шоколадный вкус и знакомое уютное настроение.',
                'ingredients' => 'Молоко, какао-порошок, шоколадный соус.',
                'volume' => 'M / L / XL',
                'price' => 210,
                'size_options' => [
                    ['label' => 'M', 'price' => 210],
                    ['label' => 'L', 'price' => 240],
                    ['label' => 'XL', 'price' => 270],
                ],
                'image_path' => 'media/images/какао.jpg',
                'sort_order' => 130,
            ],
            [
                'name' => 'Горячий шоколад',
                'slug' => 'hot-chocolate',
                'catalog' => 'menu',
                'category_key' => 'non-coffee',
                'category_name' => 'Без кофе',
                'description' => 'Плотный сладкий напиток для тех, кому хочется десерт в стакане.',
                'ingredients' => 'Молоко, шоколад, шоколадный соус.',
                'volume' => 'M / L',
                'price' => 230,
                'size_options' => [
                    ['label' => 'M', 'price' => 230],
                    ['label' => 'L', 'price' => 260],
                ],
                'image_path' => 'media/images/горячий-шоколад.jpg',
                'sort_order' => 140,
            ],
            [
                'name' => 'Айс какао',
                'slug' => 'iced-cocoa',
                'catalog' => 'menu',
                'category_key' => 'non-coffee',
                'category_name' => 'Без кофе',
                'description' => 'Холодный шоколадный напиток с мягкой текстурой и легкой свежестью.',
                'ingredients' => 'Молоко, какао-порошок, лед, шоколадный соус.',
                'volume' => 'M / L / XL',
                'price' => 240,
                'size_options' => [
                    ['label' => 'M', 'price' => 240],
                    ['label' => 'L', 'price' => 270],
                    ['label' => 'XL', 'price' => 300],
                ],
                'image_path' => 'media/images/айс-какао.jpg',
                'sort_order' => 150,
            ],
            [
                'name' => 'Бленд для эспрессо',
                'slug' => 'espresso-beans-home',
                'catalog' => 'home',
                'category_key' => 'beans',
                'category_name' => 'Кофе в зернах',
                'description' => 'Сбалансированное зерно для домашней кофемашины: плотное тело, шоколад и орех в послевкусии.',
                'ingredients' => '100% кофе в зернах, смесь арабики и робусты.',
                'volume' => '250 г / 1000 г',
                'price' => 590,
                'size_options' => [
                    ['label' => '250 г', 'price' => 590],
                    ['label' => '1000 г', 'price' => 1790],
                ],
                'image_path' => 'media/images/coffee-bag.png',
                'sort_order' => 210,
            ],
            [
                'name' => 'Бленд для фильтра',
                'slug' => 'filter-beans-home',
                'catalog' => 'home',
                'category_key' => 'beans',
                'category_name' => 'Кофе в зернах',
                'description' => 'Более мягкий и чистый профиль для воронки, капельной кофеварки и френч-пресса.',
                'ingredients' => '100% арабика в зернах.',
                'volume' => '250 г / 1000 г',
                'price' => 650,
                'size_options' => [
                    ['label' => '250 г', 'price' => 650],
                    ['label' => '1000 г', 'price' => 1980],
                ],
                'image_path' => 'media/images/home-coffee.jpg',
                'sort_order' => 220,
            ],
            [
                'name' => 'Горячий шоколад домой',
                'slug' => 'hot-chocolate-home',
                'catalog' => 'home',
                'category_key' => 'hot-chocolate-home',
                'category_name' => 'Горячий шоколад',
                'description' => 'Плотный шоколадный микс, чтобы варить дома густой и насыщенный напиток.',
                'ingredients' => 'Какао, сахар, шоколадная основа.',
                'volume' => '250 г / 500 г',
                'price' => 420,
                'size_options' => [
                    ['label' => '250 г', 'price' => 420],
                    ['label' => '500 г', 'price' => 760],
                ],
                'image_path' => 'media/images/горячий-шоколад.jpg',
                'sort_order' => 230,
            ],
            [
                'name' => 'Какао домой',
                'slug' => 'cocoa-home',
                'catalog' => 'home',
                'category_key' => 'cocoa-home',
                'category_name' => 'Какао',
                'description' => 'Домашний какао-микс для уютных кружек, мягкого вкуса и быстрого приготовления.',
                'ingredients' => 'Какао-порошок, сахар, молочная основа.',
                'volume' => '250 г / 500 г',
                'price' => 350,
                'size_options' => [
                    ['label' => '250 г', 'price' => 350],
                    ['label' => '500 г', 'price' => 620],
                ],
                'image_path' => 'media/images/какао.jpg',
                'sort_order' => 240,
            ],
        ];

        Drink::query()->whereNotIn('slug', array_column($drinks, 'slug'))->delete();

        foreach ($drinks as $drink) {
            Drink::updateOrCreate(
                ['slug' => $drink['slug']],
                $drink,
            );
        }
    }
}
